################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
C_SRCS := 
CPP_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
main \
build/xtensa-debug-module \
build/wpa_supplicant/src/wps \
build/wpa_supplicant/src/wpa2/utils \
build/wpa_supplicant/src/wpa2/tls \
build/wpa_supplicant/src/wpa2/eap_peer \
build/wpa_supplicant/src/fast_crypto \
build/wpa_supplicant/src/crypto \
build/wpa_supplicant/port \
build/wifi_service/src \
build/wifi_service/smart_config \
build/wifi_service/blufi_config \
build/wifi_service/airkiss_config \
build/wear_levelling \
build/vfs \
build/ulp \
build/tcpip_adapter \
build/tcp_transport \
build/spiffs \
build/spiffs/spiffs/src \
build/spi_flash \
build/soc/esp32 \
build/smartconfig_ack \
build/sdmmc \
build/pthread \
build/openssl/platform \
build/openssl/library \
build/nvs_flash/src \
build/nghttp/port \
build/nghttp/nghttp2/lib \
build/newlib \
build/micro-ecc/micro-ecc \
build/mdns \
build/mbedtls/port \
build/mbedtls/mbedtls/library \
build/main \
build/lwip/port \
build/lwip/port/netif \
build/lwip/port/freertos \
build/lwip/port/debug \
build/lwip/netif \
build/lwip/core \
build/lwip/core/ipv6 \
build/lwip/core/ipv4 \
build/lwip/apps/sntp \
build/lwip/apps/ping \
build/lwip/apps \
build/lwip/api \
build/log \
build/libsodium/port \
build/libsodium/port/crypto_hash_mbedtls \
build/libsodium/libsodium/src/libsodium/sodium \
build/libsodium/libsodium/src/libsodium/randombytes \
build/libsodium/libsodium/src/libsodium/crypto_verify/sodium \
build/libsodium/libsodium/src/libsodium/crypto_stream/xsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/salsa20/ref \
build/libsodium/libsodium/src/libsodium/crypto_stream \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20 \
build/libsodium/libsodium/src/libsodium/crypto_stream/chacha20/ref \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519 \
build/libsodium/libsodium/src/libsodium/crypto_sign/ed25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_sign \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24 \
build/libsodium/libsodium/src/libsodium/crypto_shorthash/siphash24/ref \
build/libsodium/libsodium/src/libsodium/crypto_shorthash \
build/libsodium/libsodium/src/libsodium/crypto_secretbox/xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_secretbox \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_scalarmult \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256 \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse \
build/libsodium/libsodium/src/libsodium/crypto_pwhash \
build/libsodium/libsodium/src/libsodium/crypto_pwhash/argon2 \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna \
build/libsodium/libsodium/src/libsodium/crypto_onetimeauth \
build/libsodium/libsodium/src/libsodium/crypto_kx \
build/libsodium/libsodium/src/libsodium/crypto_kdf \
build/libsodium/libsodium/src/libsodium/crypto_kdf/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha512 \
build/libsodium/libsodium/src/libsodium/crypto_hash/sha256 \
build/libsodium/libsodium/src/libsodium/crypto_hash \
build/libsodium/libsodium/src/libsodium/crypto_generichash \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b/ref \
build/libsodium/libsodium/src/libsodium/crypto_generichash/blake2b \
build/libsodium/libsodium/src/libsodium/crypto_core/salsa/ref \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20/ref2 \
build/libsodium/libsodium/src/libsodium/crypto_core/hsalsa20 \
build/libsodium/libsodium/src/libsodium/crypto_core/hchacha20 \
build/libsodium/libsodium/src/libsodium/crypto_core/curve25519/ref10 \
build/libsodium/libsodium/src/libsodium/crypto_box/curve25519xsalsa20poly1305 \
build/libsodium/libsodium/src/libsodium/crypto_box \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512256 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha512 \
build/libsodium/libsodium/src/libsodium/crypto_auth/hmacsha256 \
build/libsodium/libsodium/src/libsodium/crypto_auth \
build/libsodium/libsodium/src/libsodium/crypto_aead/xchacha20poly1305/sodium \
build/libsodium/libsodium/src/libsodium/crypto_aead/chacha20poly1305/sodium \
build/json/cJSON \
build/jsmn/src \
build/input_key_service \
build/http_server/src/util \
build/http_server/src \
build/heap \
build/freertos \
build/fatfs/src \
build/expat/port \
build/expat/library \
build/ethernet/eth_phy \
build/ethernet \
build/espmqtt \
build/espmqtt/lib \
build/esp_peripherals \
build/esp_peripherals/lib/touch \
build/esp_peripherals/lib/sdcard \
build/esp_peripherals/lib/button \
build/esp_peripherals/lib/blufi \
build/esp_peripherals/lib/adc_button \
build/esp_peripherals/lib/IS31FL3216 \
build/esp_peripherals/driver/i2c_bus \
build/esp_https_ota/src \
build/esp_http_client/lib \
build/esp_http_client \
build/esp_deamon \
build/esp_adc_cal \
build/esp32 \
build/esp32/hwcrypto \
build/esp-tls \
build/esp-adf-libs/esp_codec \
build/dueros_service \
build/driver \
build/display_service/led_indicator \
build/display_service/led_bar \
build/display_service \
build/cxx \
build/console \
build/console/linenoise \
build/console/argtable3 \
build/coap/port \
build/coap/libcoap/src \
build/bt \
build/bootloader_support/src \
build/bootloader/spi_flash \
build/bootloader/soc/esp32 \
build/bootloader/micro-ecc/micro-ecc \
build/bootloader/main \
build/bootloader/log \
build/bootloader/bootloader_support/src \
build/audio_stream \
build/audio_service \
build/audio_sal \
build/audio_pipeline \
build/audio_hal/driver/es8388 \
build/audio_hal/board/lyrat_v4_3 \
build/audio_hal/board \
build/audio_hal \
build/app_update \
build/app_trace \
build/app_trace/gcov \
build/adf_utils \
build/adf_utils/cloud_services \

